import { Match, LiveMatch, Predictor, CommunityPrediction, PostedSlip } from './types';

export const MATCHES: Match[] = [
  // --- UPCOMING (4) ---
  {
    id: '1',
    homeTeam: 'Arsenal',
    awayTeam: 'Man City',
    homeLogo: '🔴',
    awayLogo: '🔵',
    league: 'Premier League',
    time: '16:30',
    predictedScore: '2-1',
    predictedOutcome: 'Home Win',
    winProb: 45,
    drawProb: 25,
    lossProb: 30,
    over25: 65,
    btts: 70,
    homeForm: ['W', 'W', 'D', 'W', 'L'],
    awayForm: ['W', 'W', 'W', 'D', 'W'],
    h2h: 'Arsenal won 3 of last 5 meetings',
    confidence: 'High',
    status: 'upcoming'
  },
  {
    id: '2',
    homeTeam: 'Real Madrid',
    awayTeam: 'Barcelona',
    homeLogo: '⚪',
    awayLogo: '🔵🔴',
    league: 'La Liga',
    time: '21:00',
    predictedScore: '2-2',
    predictedOutcome: 'Both Teams To Score',
    winProb: 35,
    drawProb: 30,
    lossProb: 35,
    over25: 80,
    btts: 85,
    homeForm: ['W', 'D', 'W', 'W', 'W'],
    awayForm: ['W', 'W', 'L', 'W', 'W'],
    h2h: '2 draws in last 5 El Clasicos',
    confidence: 'Medium',
    status: 'upcoming'
  },
  {
    id: '3',
    homeTeam: 'Enyimba',
    awayTeam: 'Remo Stars',
    homeLogo: '🐘',
    awayLogo: '🌟',
    league: 'NPFL',
    time: '15:00',
    predictedScore: '1-0',
    predictedOutcome: 'Home Win',
    winProb: 60,
    drawProb: 25,
    lossProb: 15,
    over25: 30,
    btts: 40,
    homeForm: ['W', 'W', 'D', 'L', 'W'],
    awayForm: ['D', 'L', 'W', 'D', 'L'],
    h2h: 'Enyimba unbeaten in 4 home vs Remo',
    confidence: 'High',
    status: 'upcoming'
  },
  {
    id: '4',
    homeTeam: 'Liverpool',
    awayTeam: 'Chelsea',
    homeLogo: '🔴',
    awayLogo: '🔵',
    league: 'Premier League',
    time: '14:00',
    predictedScore: '2-0',
    predictedOutcome: 'Home Win',
    winProb: 50,
    drawProb: 30,
    lossProb: 20,
    over25: 55,
    btts: 45,
    homeForm: ['W', 'D', 'W', 'W', 'L'],
    awayForm: ['L', 'W', 'D', 'L', 'D'],
    h2h: 'Liverpool won last 2 meetings',
    confidence: 'High',
    status: 'upcoming'
  },
  // --- LIVE (3) ---
  {
    id: '5',
    homeTeam: 'Juventus',
    awayTeam: 'Inter Milan',
    homeLogo: '⚪⚫',
    awayLogo: '🔵⚫',
    league: 'Serie A',
    time: '19:45',
    predictedScore: '1-1',
    predictedOutcome: 'Draw',
    winProb: 30,
    drawProb: 40,
    lossProb: 30,
    over25: 40,
    btts: 60,
    homeForm: ['D', 'W', 'D', 'W', 'W'],
    awayForm: ['W', 'W', 'W', 'D', 'W'],
    h2h: 'Inter won 1-0 in last meeting',
    confidence: 'Medium',
    status: 'live',
    liveScore: { home: 1, away: 1 },
    liveMinute: 42
  },
  {
    id: '6',
    homeTeam: 'PSG',
    awayTeam: 'Marseille',
    homeLogo: '🗼',
    awayLogo: '🔵',
    league: 'Ligue 1',
    time: '20:00',
    predictedScore: '2-1',
    predictedOutcome: 'Home Win',
    winProb: 60,
    drawProb: 20,
    lossProb: 20,
    over25: 75,
    btts: 65,
    homeForm: ['W', 'W', 'W', 'W', 'W'],
    awayForm: ['L', 'L', 'W', 'D', 'W'],
    h2h: 'PSG won last 3 Classiques',
    confidence: 'High',
    status: 'live',
    liveScore: { home: 1, away: 0 },
    liveMinute: 67
  },
  {
    id: '7',
    homeTeam: 'Sporting CP',
    awayTeam: 'Benfica',
    homeLogo: '🦁',
    awayLogo: '🦅',
    league: 'Liga Portugal',
    time: '20:30',
    predictedScore: '2-2',
    predictedOutcome: 'Over 2.5',
    winProb: 35,
    drawProb: 30,
    lossProb: 35,
    over25: 80,
    btts: 85,
    homeForm: ['W', 'W', 'W', 'W', 'W'],
    awayForm: ['W', 'L', 'W', 'W', 'W'],
    h2h: 'Sporting won 2-1 in last meeting',
    confidence: 'Medium',
    status: 'live',
    liveScore: { home: 2, away: 2 },
    liveMinute: 88
  },
  // --- FINISHED (5) ---
  {
    id: '8',
    homeTeam: 'Newcastle',
    awayTeam: 'Spurs',
    homeLogo: '⚪⚫',
    awayLogo: '⚪',
    league: 'Premier League',
    time: '12:30',
    predictedScore: '3-2',
    predictedOutcome: 'Home Win',
    winProb: 40,
    drawProb: 20,
    lossProb: 40,
    over25: 90,
    btts: 90,
    homeForm: ['L', 'W', 'D', 'W', 'W'],
    awayForm: ['W', 'L', 'W', 'W', 'D'],
    h2h: 'High scoring games in last 3 meetings',
    confidence: 'High',
    status: 'finished',
    finalScore: { home: 4, away: 0 },
    predictionCorrect: true
  },
  {
    id: '9',
    homeTeam: 'Leverkusen',
    awayTeam: 'Stuttgart',
    homeLogo: '🔴⚫',
    awayLogo: '⚪🔴',
    league: 'Bundesliga',
    time: '15:30',
    predictedScore: '2-1',
    predictedOutcome: 'Home Win',
    winProb: 65,
    drawProb: 20,
    lossProb: 15,
    over25: 75,
    btts: 70,
    homeForm: ['W', 'W', 'W', 'W', 'W'],
    awayForm: ['W', 'W', 'W', 'D', 'W'],
    h2h: 'Leverkusen unbeaten this season',
    confidence: 'High',
    status: 'finished',
    finalScore: { home: 2, away: 2 },
    predictionCorrect: false
  },
  {
    id: '10',
    homeTeam: 'Aston Villa',
    awayTeam: 'Man Utd',
    homeLogo: '🦁',
    awayLogo: '🔴',
    league: 'Premier League',
    time: '15:00',
    predictedScore: '1-2',
    predictedOutcome: 'Away Win',
    winProb: 30,
    drawProb: 25,
    lossProb: 45,
    over25: 65,
    btts: 70,
    homeForm: ['L', 'W', 'L', 'D', 'W'],
    awayForm: ['W', 'W', 'W', 'W', 'D'],
    h2h: 'Villa won last home meeting 3-1',
    confidence: 'Medium',
    status: 'finished',
    finalScore: { home: 1, away: 2 },
    predictionCorrect: true
  },
  {
    id: '11',
    homeTeam: 'Celtic',
    awayTeam: 'Rangers',
    homeLogo: '🍀',
    awayLogo: '🔵',
    league: 'Scottish Premiership',
    time: '12:30',
    predictedScore: '2-1',
    predictedOutcome: 'Home Win',
    winProb: 45,
    drawProb: 25,
    lossProb: 30,
    over25: 70,
    btts: 75,
    homeForm: ['W', 'W', 'D', 'W', 'W'],
    awayForm: ['W', 'W', 'W', 'L', 'W'],
    h2h: 'Celtic unbeaten in last 3 Old Firms',
    confidence: 'High',
    status: 'finished',
    finalScore: { home: 3, away: 3 },
    predictionCorrect: false
  },
  {
    id: '12',
    homeTeam: 'Napoli',
    awayTeam: 'Roma',
    homeLogo: '🔵',
    awayLogo: '🔴🟡',
    league: 'Serie A',
    time: '18:00',
    predictedScore: '1-0',
    predictedOutcome: 'Home Win',
    winProb: 50,
    drawProb: 30,
    lossProb: 20,
    over25: 35,
    btts: 45,
    homeForm: ['L', 'D', 'W', 'L', 'D'],
    awayForm: ['W', 'W', 'D', 'W', 'W'],
    h2h: 'Roma won 2-0 in last meeting',
    confidence: 'Medium',
    status: 'finished',
    finalScore: { home: 2, away: 1 },
    predictionCorrect: true
  }
];

export const BANKER_OF_THE_DAY: Match = {
  ...MATCHES[0],
  confidence: 'High',
  predictedOutcome: 'Home Win',
};

export const LIVE_MATCHES: LiveMatch[] = [
  {
    id: 'l1',
    homeTeam: 'Crystal Palace',
    awayTeam: 'Everton',
    homeScore: 1,
    awayScore: 0,
    league: 'Premier League',
    minute: '67',
    isLive: true,
    status: 'Live'
  },
  {
    id: 'l2',
    homeTeam: 'Getafe',
    awayTeam: 'Villarreal',
    homeScore: 0,
    awayScore: 2,
    league: 'La Liga',
    minute: '42',
    isLive: true,
    status: 'Live'
  },
  {
    id: 'l3',
    homeTeam: 'AC Milan',
    awayTeam: 'Napoli',
    homeScore: 3,
    awayScore: 1,
    league: 'Serie A',
    minute: 'FT',
    isLive: false,
    status: 'FT'
  }
];

export const PREDICTORS: Predictor[] = [];

export const POSTED_SLIPS: PostedSlip[] = [];

export const COMMUNITY_PREDICTIONS: CommunityPrediction[] = [];
